### ISSUE TITLE
Installing with .[gpu_optimization] do not work ?

### ISSUE THREAD

**Issue by eliebak** [Aleph-Alpha/scaling#1]
Not a big issue just to let you know. I have to first do pip install -e . => Then do pip install -e .[gpu_optimization] because otherwise i get an error with torch not installed.

See full log here:
```
(scaling) $ pip install -e .[gpu_optimization]
Obtaining file:///fsx/elie_bakouch/scaling
  Preparing metadata (setup.py) ... done
Collecting torch==2.1.1 (from aleph-alpha-scaling==0.1.0)
  Using cached torch-2.1.1-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Collecting torchvision==0.16.1 (from aleph-alpha-scaling==0.1.0)
  Using cached torchvision-0.16.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting blended-dataset-loop==0.1 (from aleph-alpha-scaling==0.1.0)
  Using cached blended_dataset_loop-0.1.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pydantic==2.8.2 (from aleph-alpha-scaling==0.1.0)
  Using cached pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
Collecting einops (from aleph-alpha-scaling==0.1.0)
  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Collecting pyyaml (from aleph-alpha-scaling==0.1.0)
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting numpy==1.26.4 (from aleph-alpha-scaling==0.1.0)
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting tensorboard (from aleph-alpha-scaling==0.1.0)
  Using cached tensorboard-2.17.1-py3-none-any.whl.metadata (1.6 kB)
Collecting tqdm (from aleph-alpha-scaling==0.1.0)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting python-dateutil (from aleph-alpha-scaling==0.1.0)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tokenizers (from aleph-alpha-scaling==0.1.0)
  Using cached tokenizers-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting pillow (from aleph-alpha-scaling==0.1.0)
  Using cached pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Collecting wandb (from aleph-alpha-scaling==0.1.0)
  Using cached wandb-0.17.7-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting cffi (from blended-dataset-loop==0.1->aleph-alpha-scaling==0.1.0)
  Using cached cffi-1.17.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting annotated-types>=0.4.0 (from pydantic==2.8.2->aleph-alpha-scaling==0.1.0)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.20.1 (from pydantic==2.8.2->aleph-alpha-scaling==0.1.0)
  Using cached pydantic_core-2.20.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.6.1 (from pydantic==2.8.2->aleph-alpha-scaling==0.1.0)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting filelock (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting sympy (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.18.1 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.1.0 (from torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting requests (from torchvision==0.16.1->aleph-alpha-scaling==0.1.0)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.1.1->aleph-alpha-scaling==0.1.0)
  Using cached nvidia_nvjitlink_cu12-12.6.20-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting flash-attn==2.4.2 (from aleph-alpha-scaling==0.1.0)
  Using cached flash_attn-2.4.2.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8cmqrek7/flash-attn_cf22286edbdf481ba93a6259905e9f14/setup.py", line 19, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by artur-baranowski-aa** [comment]
Thank you @eliebak , we will precise the installation instructions. Flash Attention currently requires torch to be (pre-)installed, see also for reference: https://github.com/Dao-AILab/flash-attention/issues/246
